### ISSUE TITLE
Too much magic?

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#3]
The current implementation follows SwiftPM's example of injecting some compile args, specifically `-j8` and `-sdk [sdk]` (on OSX).

I know we desire to have zero magic, but you might be insane if you compile any program without those flags.  Should we really require users to specify that in the target configuration?

**Comment by owensd** [comment]
We can elevate the magic by putting those flags as a default values on configs?

**Comment by drewcrawford** [comment]
Well as you said, platforms are just configs.  I think it is too much magic if `darwin` behaves differently from `osx` from `macosx` for example.  We can't catch them all.

Here's an idea.  What if this was a default setting for `atllbuild` e.g.

``` yaml
tasks:
    build:
        tool: atllbuild
        name: json-swift #name of the thing being built
        output-type: library
        source: ["src/**.swift"]
        lessMagic: true #stop injecting any args
```

(update for closure syntax)

By default the value is `false` and so you get some injection, but we document this setting so a power user can override.
